### ISSUE TITLE
Are signatures properly checked?

### ISSUE THREAD

**Issue by bedeho** [bitpay/bitcore-channel#23]
The consumer validates the refund in validateRefund(),
and the the provider validates paments in validatePayment(), both by doing

Script.Interpreter().verify( *.inputs[0].script, *.inputs[0].output.script )

However, this call does not provide the spending transaction, which should be required since the scriptSig (*.inputs[0].script) contains a multisig redeem script based on OP_CHECKMULTISIG?

As the docs for verify() state:

@param {Transaction=} tx - the Transaction containing the scriptSig in one input (used * to check signature validity for some opcodes like OP_CHECKSIG)

The flag argument, which allows validation of P2SH by using Interpreter.SCRIPT_VERIFY_P2SH, is also missing.

Does this actually do a proper signature check?

**Comment by braydonf** [comment]
Good catch, thanks! Included in: https://github.com/bitpay/bitcore-channel/commit/c69e9679f1f8774d666b54c4f6682d595d26b2cd
