### ISSUE TITLE
Payment.prototype._updateTransaction calls nonexistant functions

### ISSUE THREAD

**Issue by snakecharmer1024** [bitpay/bitcore-channel#30]
this.clearOutputs();

no such clearOutputs function in bitcore.js or bitcore-channel.js

**Comment by maraoz** [comment]
Yes there is: https://github.com/bitpay/bitcore/blob/master/lib/transaction/transaction.js#L726

Do you have the latest bitcore version?

**Comment by snakecharmer1024** [comment]
Clearly not. Sorry for the false alarm.
